name: "Chromatic"

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    outputs:
      buildUrl: ${{ steps.chromatic.outputs.buildUrl }}
      storybookUrl: ${{ steps.chromatic.outputs.storybookUrl }}
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: npm install
      - name: Publish to Chromatic
        uses: chromaui/action@v1
        id: chromatic
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          exitZeroOnChanges: true

  comment:
    needs: [deploy]
    name: Comment
    uses: ./.github/workflows/comment.yml
    with:
      comment_secret: af509cd3-e034-490e-9a0e-93625c124f76
      template: .github/chromatic-comment-template.md
      variable1: ${{ needs.deploy.outputs.buildUrl }}
      variable2: ${{ needs.deploy.outputs.storybookUrl }}
