name: "Deploy main"

on: 
  workflow_dispatch:
    inputs:
      force:
        type: boolean
        description: "Use --force when pushing to main"
        required: true
        default: false

jobs:
  sync-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Git checkout
        with:
          token: ${{ github.token }}
          fetch-depth: 0
      - name: Merge develop into main
        run: |
          git config user.name "GitHub Actions"
          git config user.email "wojciech.lechowicz@intive.com"
          git checkout main
          git pull origin develop
          git push origin main ${{ github.event.inputs.force == true && '--force' || '' }}
