name: "develop -> main"

on:
  workflow_dispatch:
    inputs:
      force:
        type: boolean
        description: "Use --force when pushing to main"
        required: true
        default: false

jobs:
  sync-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Git checkout
        with:
          token: ${{ secrets.GH_PUSH_TOKEN }}
          fetch-depth: 0
      - name: Merge develop into main
        run: |
          git config user.name "GitHub Actions"
          git config user.email "wojciech.lechowicz@intive.com"
          git checkout main
          echo "pull develop into main"
          git pull origin develop
          echo "push to origin main"
          git push origin main ${{ github.event.inputs.force == true && '--force' || '' }}
