name: Deploy main

jobs:
  sync-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Merge develop -> main
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: develop
          target_branch: main
          github_token: ${{ github.token }}
